### ISSUE TITLE
Provided binaries do not work

### ISSUE THREAD

**Issue by LeoWelter** [wassermanlab/JASPAR-UCSC-tracks#10]
The provided binaries of matrix_scan and matrix_probe do not work on any of my Linux systems. (RH7 and Ubuntu 16.0x-20.0x

Do you have a working Linux binary available?

**Comment by oriolfornes** [comment]
Hi Leo, I am afraid I provided a set of binaries compiled from my Mac. I have updated the repo with the script [`install-pwmscan.sh`](https://github.com/wassermanlab/JASPAR-UCSC-tracks/blob/master/install-pwmscan.sh), which automatically downloads and installs PWMscan for you and places the binaries in the bin folder.
