### ISSUE TITLE
2022 v 2020 danRer11 tracks changed from using TF name to matrix identifier possibly in error

### ISSUE THREAD

**Issue by malcook** [wassermanlab/JASPAR-UCSC-tracks#11]
While comparing

http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2020/JASPAR2020_danRer11.bb
http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2022/JASPAR2022_danRer11.bb

I find that the 2022 bigbed files display the matrix identifiers while those for 2020 display the TF name, at least as displayed in IGV, as pictured below.

I expect this is in error.

![image](https://user-images.githubusercontent.com/484282/148460635-82ff02c5-5b84-4475-82a2-e71f3db129bc.png)
![image](https://user-images.githubusercontent.com/484282/148460710-2f72c661-a47e-4e7e-b207-c1fb8d7b9490.png)

**Comment by amathelier** [comment]
This is expected. We changed that since a TF can have multiple TF binding profiles in JASPAR. To avoid confusion about which profile is used, we now provide the profile name. Nevertheless, the bigbeds contain the TF name as an extra field.
