### ISSUE TITLE
p_value clarification needed on their scaling and interpretation 

### ISSUE THREAD

**Issue by malcook** [wassermanlab/JASPAR-UCSC-tracks#12]
In [JASPAR UCSC tracks](https://github.com/wassermanlab/JASPAR-UCSC-tracks/blob/master/README.md) I read that scores in the bigbed files are p-values which have benn
>     (scaled between 0-1000, where 0 corresponds to p-value = 1 and 1000 to p-value ≤ 10-10)

Can I use R's [rescale](https://www.rdocumentation.org/packages/scales/versions/0.4.1/topics/rescale) function to recover the p-values from the scores?  For instance, a score of 950 comes from a p-value of .05

```
library(scales)
rescale(950,c(1,10**-10),c(0,1000))
.05
```
In any case, I am having trouble effectively interpreting the p_value. 

In [PWMScan: a fast tool for scanning entire genomes with a position\-specific weight matrix](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6041753/) I read
> The P-value of a PWM score x is defined as the probability that a random k-mer sequence of the length of the PWM has a binding score ≥ x given the base composition of the genome.

I would hope to find some measure of how well the sequence at a candidate (or putative) binding site identified by PWMScan matches the motif PWM.  This does not seem to provide that.  Or am I mistaken?

I would like possibility of being more stringent in selection of candidates from this trace by setting a threshold on the score.  However, I am hesitant to adopt this approach as thresholding on the scaled P_value could introduce a bias toward a subset of the universe of motifs.  Is my reasoning suspect here?

_edit:_ Perhaps another way of getting at this is to ask: **do the motifs have the same distribution of P_values as each other?.**  If they do, then thresholding across the board at any given P_value should remove an equal fraction of each motif's hits.  Do you know if they do?

**Comment by oriolfornes** [comment]
Dear Malcom,

I believe that the re-scaling that you are applying is incorrect.

The applied p-value transformation is: int(log10(p-value) * 1000 / -10)

Therefore, a 0.05 p-value would correspond to a score of *130*:

>>> p = .05
>>> import numpy as np
>>> int(np.log10(p) * 1000 / -10)
130


What you want is the *relative score* of your predictions.
That is, for a given motif hit with PWMScan, what is the relative score
between 0 and 1, where 0 is the score of the worst possible hit using this
profile, and 1 is the maximum score that can be attained using that same
profile.
Unfortunately, relative scores are not comparable across TFs: a relative
score of 0.9 with motif A could be less stringent than a score of 0.85 with
motif B.
This is why in the UCSC genome tracks we include these "transformed''
p-values.

You can find the genome-wide predictions for different model organisms used
for the generation of the UCSC genome tracks here:
http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2022/
I believe that column five of each TSV file is the relative score from
PWMScan that you are looking for.

--

*Oriol Fornés Crespo, PhD*Research Associate / Wasserman Lab
***@***.***

Centre for Molecular Medicine and Therapeutics (CMMT)
Dpt. of Medical Genetics / University of British Columbia
BC Children's Hospital Research Institute
950 W 28th Ave, Room 3109, Vancouver, BC V5Z 4H4, Canada

**Comment by malcook** [comment]
thanks for education!
