### ISSUE TITLE
mismatched taxon

### ISSUE THREAD

**Issue by NanaMatoba** [wassermanlab/JASPAR-UCSC-tracks#13]
Hi, thank you for the great resources.

I'm looking at hg38 [http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2022/hg38/](http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2022/hg38/)
 and found some motifs that seem unrelated to Vertebrata, for example, MA2020 is from Arabidopsis thaliana. MA1879 is from Ciona intestinalis (these are just examples and there are more).

I see the option  `--taxon vertebrate` for hg38 in your code [https://github.com/wassermanlab/JASPAR-UCSC-tracks/blob/master/scan-sequences.sh](https://github.com/wassermanlab/JASPAR-UCSC-tracks/blob/master/scan-sequences.sh)
, so I assumed that only motifs linked to vertebrates are included.

Since other genome versions like hg19 or mm10 also include the non-vertebrate motif annotation, I wondered if it's intended or if there are some mistakes.

Thank you!
Nana

**Comment by NanaMatoba** [comment]
looks like you guys updated the data, but it would be great if you can confirm.

Thank you again.
Nana

**Comment by oriolfornes** [comment]
Yes, we did. I was gonna ensure that everything was fixed before replying. Briefly, between submission and final publication of JASPAR 2022 there was an update in the profile numbering that was not handled properly when I rsync'ed the scans. I recomputed everything again. It should be correct now.
