### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by luisafmc** [wassermanlab/JASPAR-UCSC-tracks#14]
Hi, 
Thank you for the development of [JASPAR-UCSC-tracks](https://github.com/wassermanlab/JASPAR-UCSC-tracks)

I am very interested in using this program. However, I try to install the program by the bash execution of the script [install-pwmscan.sh](https://github.com/wassermanlab/JASPAR-UCSC-tracks/blob/master/install-pwmscan.sh). However, the following error shows every time:

gcc -fPIC -O3 -std=gnu99 -W -Wall -o hashtable.o -c hashtable.c
make: gcc: Command not found
make: *** [Makefile:42: hashtable.o] Error 127

Could you help me? 

Thank you!

**Comment by oriolfornes** [comment]
Hi Luisa, you need to install [gcc](https://gcc.gnu.org/). If you do not know how, I suggest that you contact your sys admin.
