### ISSUE TITLE
fetch -p parameter

### ISSUE THREAD

**Issue by robinvanderlee** [wassermanlab/JASPAR-UCSC-tracks#4]
@oriolfornes 

Shouldn't this part from the fetch* script not be "from jaspar2pfm.py"  rather than from "jaspar2meme.py"?

`parser.add_option("-p", action="store", type="string", dest="profiles_dir", help="Profiles directory (from jaspar2meme.py)", metavar="<profiles_dir>")
`

**Comment by oriolfornes** [comment]
NO!


--
Oriol Fornés Crespo, PhD
Postdoctoral Fellow @ Wasserman lab
Centre for Molecular Medicine and Therapeutics (CMMT)
University of British Columbia
BC Children's Hospital Research Institute
980 W 28th Ave, Room 3109, Vancouver, BC V5Z 4H4, Canada
E-mail: oriol@cmmt.ubc.ca

On Tue, Sep 19, 2017 at 3:30 PM, Robin van der Lee <notifications@github.com
